name: Java JThumbnail Build
#
on: [ push, workflow_dispatch ]
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Download and extract OpenOffice
        run: |
          # Define the OpenOffice version you want to download
          LO_VERSION=25.8.0

          # Define the URL for the OpenOffice installation package ${LO_VERSION}
          LO_URL=https://download.documentfoundation.org/libreoffice/stable/${LO_VERSION}/deb/x86_64/LibreOffice_${LO_VERSION}_Linux_x86-64_deb.tar.gz
          
          # Create the target directory
          mkdir -p ~/tools/soffice/

          # Download the LibreOffice package
          curl -L -o ~/tools/soffice/libreOffice.tar.gz $LO_URL

          # Extract OpenOffice
          tar -xzf ~/tools/soffice/libreOffice.tar.gz --strip-components=1 -C ~/tools/soffice/

          # Install OpenOffice (you may need to adapt this step depending on your requirements)
          sudo dpkg -i ~/tools/soffice/DEBS/*.deb

        working-directory: ${{ github.workspace }}

      - name: Build
        env:
          jthumbnailer.openoffice.working-dir: /tmp/
          jthumbnailer.openoffice.office_home: /opt/libreoffice25.8/
          jthumbnailer.openoffice.dir: /opt/libreoffice25.8/

        run: ./gradlew test --stacktrace --info -Djava.library.path=/opt/libreoffice25.8/program/

  publish:
#    needs: [ "build" ]
    if: contains(github.ref_name, 'dev/')
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Deploy to GitHub Packages
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          GITHUB_USERNAME: makbn
          GITHUB_ACTOR: makbn
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
